"""
Fix the swoth_l3_data_plot copy.ipynb notebook:
1. Add all_cycle_dirs = [] before the os.walk loop
2. Fix PROCESS_ALL_CYCLES reference in grand summary
3. Add composite fwd+bwd cell
4. Add cyclone before/after analysis cell
5. Add seasonal/daily analysis cell
"""
import json, copy

NB_PATH = r"c:\Users\abhik\Desktop\project related work\swoth_l3_data_plot copy.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

print(f"Cells: {len(nb['cells'])}")
for i, c in enumerate(nb["cells"]):
    print(f"  [{i}] {c['cell_type']}  lines={len(c['source'])}")

# ── FIX 1: Cell index 1 — add `all_cycle_dirs = []` before os.walk loop ──
cell1 = nb["cells"][1]
new_source = []
inserted = False
for line in cell1["source"]:
    if not inserted and line.startswith("for root, dirs, files in os.walk(BASE_DIR):"):
        new_source.append("all_cycle_dirs = []   # initialise before the loop\n")
        new_source.append("\n")
        inserted = True
    new_source.append(line)

if inserted:
    cell1["source"] = new_source
    print("FIX 1 applied: all_cycle_dirs = [] inserted")
else:
    print("FIX 1 SKIPPED: could not find os.walk line")

# ── FIX 2: Cell index 5 — replace PROCESS_ALL_CYCLES with PROCESS_ALL ──
cell5 = nb["cells"][5]
new_source5 = []
for line in cell5["source"]:
    line = line.replace("PROCESS_ALL_CYCLES", "PROCESS_ALL")
    line = line.replace("SPECIFIC_CYCLES", "FOLDER_FILTER")
    line = line.replace('f"SPECIFIC CYCLES: {FOLDER_FILTER}"', 'f"FILTER: \'{FOLDER_FILTER}\'"')
    new_source5.append(line)
cell5["source"] = new_source5
print("FIX 2 applied: PROCESS_ALL_CYCLES → PROCESS_ALL")

# ── NEW CELL 7: Forward + Backward Composite on one image ──
composite_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===================================================================\n",
        "# FORWARD + BACKWARD PASS COMPOSITE — BOTH ON ONE IMAGE\n",
        "# ===================================================================\n",
        "from matplotlib.lines import Line2D\n",
        "\n",
        "def plot_composite_fwd_bwd(file_list, title_label, lat_bounds, lon_bounds, save_name):\n",
        '    """\n',
        "    Plot forward (odd) and backward (even) passes together on one map.\n",
        '    """\n',
        "    forward_files  = [f for f in file_list if f['pass_number'] % 2 == 1]\n",
        "    backward_files = [f for f in file_list if f['pass_number'] % 2 == 0]\n",
        "\n",
        "    fig = plt.figure(figsize=(18, 14))\n",
        "    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())\n",
        "    ax.set_extent([lon_bounds[0], lon_bounds[1], lat_bounds[0], lat_bounds[1]],\n",
        "                  crs=ccrs.PlateCarree())\n",
        "    ax.add_feature(cfeature.LAND, facecolor='lightgray', edgecolor='black', linewidth=0.5)\n",
        "    ax.add_feature(cfeature.OCEAN, facecolor='#e6f2ff', alpha=0.3)\n",
        "    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)\n",
        "    ax.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.5)\n",
        "\n",
        "    sc_any = None\n",
        "    fwd_pts = 0\n",
        "    bwd_pts = 0\n",
        "    fwd_pass_list = []\n",
        "    bwd_pass_list = []\n",
        "\n",
        "    # --- Forward passes (ascending / odd) ---\n",
        "    for f in forward_files:\n",
        "        try:\n",
        "            lat, lon, ssha, _ = load_l3_data(f['filepath'])\n",
        "            mask = ((lat >= lat_bounds[0]) & (lat <= lat_bounds[1]) &\n",
        "                    (lon >= lon_bounds[0]) & (lon <= lon_bounds[1]))\n",
        "            if np.sum(mask) > 0:\n",
        "                sc_any = ax.scatter(lon[mask], lat[mask], c=ssha[mask],\n",
        "                                    cmap='RdBu_r', s=0.5, alpha=0.8,\n",
        "                                    vmin=-0.5, vmax=0.5, marker='o',\n",
        "                                    transform=ccrs.PlateCarree())\n",
        "                fwd_pts += np.sum(mask)\n",
        "                fwd_pass_list.append(f['pass_number'])\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # --- Backward passes (descending / even) ---\n",
        "    for f in backward_files:\n",
        "        try:\n",
        "            lat, lon, ssha, _ = load_l3_data(f['filepath'])\n",
        "            mask = ((lat >= lat_bounds[0]) & (lat <= lat_bounds[1]) &\n",
        "                    (lon >= lon_bounds[0]) & (lon <= lon_bounds[1]))\n",
        "            if np.sum(mask) > 0:\n",
        "                sc_any = ax.scatter(lon[mask], lat[mask], c=ssha[mask],\n",
        "                                    cmap='RdBu_r', s=0.5, alpha=0.8,\n",
        "                                    vmin=-0.5, vmax=0.5, marker='s',\n",
        "                                    transform=ccrs.PlateCarree())\n",
        "                bwd_pts += np.sum(mask)\n",
        "                bwd_pass_list.append(f['pass_number'])\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    if sc_any is not None:\n",
        "        cbar = plt.colorbar(sc_any, ax=ax, shrink=0.7, pad=0.02)\n",
        "        cbar.set_label('SSHA (m)', fontsize=12)\n",
        "\n",
        "    gl = ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.5, linestyle='--')\n",
        "    gl.top_labels = gl.right_labels = False\n",
        "\n",
        "    legend_elements = [\n",
        "        Line2D([0], [0], marker='o', color='w', markerfacecolor='steelblue',\n",
        "               markersize=8, label=f'Forward  ({len(fwd_pass_list)} passes, {fwd_pts:,} pts)'),\n",
        "        Line2D([0], [0], marker='s', color='w', markerfacecolor='coral',\n",
        "               markersize=8, label=f'Backward ({len(bwd_pass_list)} passes, {bwd_pts:,} pts)')\n",
        "    ]\n",
        "    ax.legend(handles=legend_elements, loc='upper left', fontsize=10, framealpha=0.9)\n",
        "\n",
        "    ax.set_title(f'SWOT L3 — {title_label}\\n'\n",
        "                 f'Fwd: {fwd_pts:,} pts  |  Bwd: {bwd_pts:,} pts\\n'\n",
        "                 f'({lat_bounds[0]}°–{lat_bounds[1]}°N, {lon_bounds[0]}°–{lon_bounds[1]}°E)',\n",
        "                 fontsize=14, fontweight='bold')\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(save_name, dpi=200, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(f'  Composite saved → {save_name}')\n",
        "\n",
        "\n",
        "# --- Generate composite for each selected folder ---\n",
        "for cycle_info in selected_cycles:\n",
        "    cycle_num    = cycle_info['cycle_num']\n",
        "    cycle_dir    = cycle_info['path']\n",
        "    cycle_folder = cycle_info['folder']\n",
        "\n",
        "    nc_files = glob.glob(os.path.join(cycle_dir, '*.nc'))\n",
        "    parsed   = [p for p in (parse_l3_filename(f) for f in nc_files) if p is not None]\n",
        "    if not parsed:\n",
        "        continue\n",
        "\n",
        "    granule_map = defaultdict(list)\n",
        "    for p in parsed:\n",
        "        key = (p['cycle'], p['pass_number'],\n",
        "               p['start_datetime'].strftime('%Y%m%dT%H%M%S'))\n",
        "        granule_map[key].append(p)\n",
        "    files_info = sorted(\n",
        "        [max(v, key=lambda x: x['version']) for v in granule_map.values()],\n",
        "        key=lambda x: x['pass_number']\n",
        "    )\n",
        "\n",
        "    label     = f'{cycle_folder}' + (f' (Cycle {cycle_num:03d})' if cycle_num else '')\n",
        "    safe_name = re.sub(r'[^\\w]', '_', cycle_folder)\n",
        "\n",
        "    plot_composite_fwd_bwd(\n",
        "        files_info,\n",
        "        title_label=f'{label} — Fwd + Bwd Composite',\n",
        "        lat_bounds=LAT_BOUNDS,\n",
        "        lon_bounds=LON_BOUNDS,\n",
        "        save_name=f'composite_fwd_bwd_{safe_name}.png'\n",
        "    )\n",
    ]
}

# ── NEW CELL 8: Cyclone Before / After Analysis ──
cyclone_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===================================================================\n",
        "# CYCLONE BEFORE / AFTER ANALYSIS\n",
        "# ===================================================================\n",
        "# Define cyclone events with date ranges (10–15 days before & after)\n",
        "from datetime import timedelta\n",
        "\n",
        "CYCLONE_EVENTS = {\n",
        "    'Cyclone Shakti': {\n",
        "        'landfall': datetime(2024, 12, 14),   # adjust to actual date\n",
        "        'before_days': 15,\n",
        "        'after_days': 15,\n",
        "    },\n",
        "    'Cyclone Remal': {\n",
        "        'landfall': datetime(2024, 5, 26),\n",
        "        'before_days': 15,\n",
        "        'after_days': 15,\n",
        "    },\n",
        "    'Cyclone Dana': {\n",
        "        'landfall': datetime(2024, 10, 25),\n",
        "        'before_days': 15,\n",
        "        'after_days': 15,\n",
        "    },\n",
        "}\n",
        "\n",
        "# Collect ALL parsed files across all selected folders\n",
        "all_parsed_files = []\n",
        "for cycle_info in selected_cycles:\n",
        "    nc_files = glob.glob(os.path.join(cycle_info['path'], '*.nc'))\n",
        "    for f in nc_files:\n",
        "        p = parse_l3_filename(f)\n",
        "        if p is not None:\n",
        "            all_parsed_files.append(p)\n",
        "\n",
        "print(f'Total parsed files across all folders: {len(all_parsed_files)}')\n",
        "\n",
        "for cyc_name, cyc_info in CYCLONE_EVENTS.items():\n",
        "    landfall = cyc_info['landfall']\n",
        "    before_start = landfall - timedelta(days=cyc_info['before_days'])\n",
        "    after_end    = landfall + timedelta(days=cyc_info['after_days'])\n",
        "\n",
        "    before_files = [f for f in all_parsed_files\n",
        "                    if before_start <= f['start_datetime'] < landfall]\n",
        "    after_files  = [f for f in all_parsed_files\n",
        "                    if landfall <= f['start_datetime'] <= after_end]\n",
        "\n",
        "    print(f'\\n{\"=\"*80}')\n",
        "    print(f'  {cyc_name}  —  Landfall: {landfall.strftime(\"%Y-%m-%d\")}')\n",
        "    print(f'  Before window: {before_start.strftime(\"%Y-%m-%d\")} → {landfall.strftime(\"%Y-%m-%d\")}  ({len(before_files)} files)')\n",
        "    print(f'  After  window: {landfall.strftime(\"%Y-%m-%d\")} → {after_end.strftime(\"%Y-%m-%d\")}  ({len(after_files)} files)')\n",
        "    print(f'{\"=\"*80}')\n",
        "\n",
        "    if not before_files and not after_files:\n",
        "        print(f'  ⚠️ No data found for {cyc_name}')\n",
        "        continue\n",
        "\n",
        "    # ── Side-by-side: Before vs After ──\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(28, 12),\n",
        "                             subplot_kw={'projection': ccrs.PlateCarree()})\n",
        "\n",
        "    for ax, files, phase in zip(axes, [before_files, after_files],\n",
        "                                ['BEFORE', 'AFTER']):\n",
        "        ax.set_extent([LON_BOUNDS[0], LON_BOUNDS[1],\n",
        "                       LAT_BOUNDS[0], LAT_BOUNDS[1]], crs=ccrs.PlateCarree())\n",
        "        ax.add_feature(cfeature.LAND, facecolor='lightgray', edgecolor='black')\n",
        "        ax.add_feature(cfeature.OCEAN, facecolor='#e6f2ff', alpha=0.3)\n",
        "        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)\n",
        "        ax.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.5)\n",
        "\n",
        "        sc = None\n",
        "        total_pts = 0\n",
        "        for f in files:\n",
        "            try:\n",
        "                lat, lon, ssha, _ = load_l3_data(f['filepath'])\n",
        "                mask = ((lat >= LAT_BOUNDS[0]) & (lat <= LAT_BOUNDS[1]) &\n",
        "                        (lon >= LON_BOUNDS[0]) & (lon <= LON_BOUNDS[1]))\n",
        "                if np.sum(mask) > 0:\n",
        "                    sc = ax.scatter(lon[mask], lat[mask], c=ssha[mask],\n",
        "                                   cmap='RdBu_r', s=0.5, alpha=0.8,\n",
        "                                   vmin=-0.5, vmax=0.5,\n",
        "                                   transform=ccrs.PlateCarree())\n",
        "                    total_pts += np.sum(mask)\n",
        "            except Exception:\n",
        "                pass\n",
        "\n",
        "        if sc is not None:\n",
        "            plt.colorbar(sc, ax=ax, shrink=0.7, pad=0.02).set_label('SSHA (m)')\n",
        "\n",
        "        gl = ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.5, linestyle='--')\n",
        "        gl.top_labels = gl.right_labels = False\n",
        "\n",
        "        date_range = ''\n",
        "        if files:\n",
        "            d0 = min(f['start_datetime'] for f in files).strftime('%Y-%m-%d')\n",
        "            d1 = max(f['start_datetime'] for f in files).strftime('%Y-%m-%d')\n",
        "            date_range = f'{d0} → {d1}'\n",
        "        ax.set_title(f'{phase} {cyc_name}\\n'\n",
        "                     f'{len(files)} passes | {total_pts:,} pts\\n'\n",
        "                     f'{date_range}', fontsize=13, fontweight='bold')\n",
        "\n",
        "    fig.suptitle(f'{cyc_name} — Before vs After  (Landfall: {landfall.strftime(\"%Y-%m-%d\")})',\n",
        "                 fontsize=16, fontweight='bold', y=1.02)\n",
        "    plt.tight_layout()\n",
        "    safe = re.sub(r'[^\\w]', '_', cyc_name)\n",
        "    fname = f'cyclone_before_after_{safe}.png'\n",
        "    plt.savefig(fname, dpi=200, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(f'  Saved → {fname}')\n",
    ]
}

# ── NEW CELL 9: Season-wise / Day-wise Analysis ──
seasonal_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===================================================================\n",
        "# SEASON-WISE & DAY-WISE SSHA ANALYSIS (Mesoscale Eddies)\n",
        "# ===================================================================\n",
        "\n",
        "def get_season(dt):\n",
        "    \"\"\"Return Indian Ocean meteorological season.\"\"\"\n",
        "    m = dt.month\n",
        "    if m in (12, 1, 2):   return 'Winter (DJF)'\n",
        "    if m in (3, 4, 5):    return 'Pre-Monsoon (MAM)'\n",
        "    if m in (6, 7, 8, 9): return 'Monsoon (JJAS)'\n",
        "    return 'Post-Monsoon (OND)'\n",
        "\n",
        "# ── Group files by season ──\n",
        "season_files = defaultdict(list)\n",
        "for f in all_parsed_files:\n",
        "    season_files[get_season(f['start_datetime'])].append(f)\n",
        "\n",
        "print('Files by season:')\n",
        "for s in sorted(season_files.keys()):\n",
        "    print(f'  {s}: {len(season_files[s])} files')\n",
        "\n",
        "# ── Plot each season ──\n",
        "season_order = ['Winter (DJF)', 'Pre-Monsoon (MAM)',\n",
        "                'Monsoon (JJAS)', 'Post-Monsoon (OND)']\n",
        "present_seasons = [s for s in season_order if s in season_files]\n",
        "\n",
        "if present_seasons:\n",
        "    n = len(present_seasons)\n",
        "    fig, axes = plt.subplots(1, n, figsize=(8*n, 10),\n",
        "                             subplot_kw={'projection': ccrs.PlateCarree()})\n",
        "    if n == 1:\n",
        "        axes = [axes]\n",
        "\n",
        "    for ax, season in zip(axes, present_seasons):\n",
        "        ax.set_extent([LON_BOUNDS[0], LON_BOUNDS[1],\n",
        "                       LAT_BOUNDS[0], LAT_BOUNDS[1]], crs=ccrs.PlateCarree())\n",
        "        ax.add_feature(cfeature.LAND, facecolor='lightgray', edgecolor='black')\n",
        "        ax.add_feature(cfeature.OCEAN, facecolor='#e6f2ff', alpha=0.3)\n",
        "        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)\n",
        "        ax.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.5)\n",
        "\n",
        "        sc = None\n",
        "        pts = 0\n",
        "        for f in season_files[season]:\n",
        "            try:\n",
        "                lat, lon, ssha, _ = load_l3_data(f['filepath'])\n",
        "                mask = ((lat >= LAT_BOUNDS[0]) & (lat <= LAT_BOUNDS[1]) &\n",
        "                        (lon >= LON_BOUNDS[0]) & (lon <= LON_BOUNDS[1]))\n",
        "                if np.sum(mask) > 0:\n",
        "                    sc = ax.scatter(lon[mask], lat[mask], c=ssha[mask],\n",
        "                                   cmap='RdBu_r', s=0.3, alpha=0.7,\n",
        "                                   vmin=-0.5, vmax=0.5,\n",
        "                                   transform=ccrs.PlateCarree())\n",
        "                    pts += np.sum(mask)\n",
        "            except Exception:\n",
        "                pass\n",
        "\n",
        "        if sc is not None:\n",
        "            plt.colorbar(sc, ax=ax, shrink=0.6, pad=0.02).set_label('SSHA (m)')\n",
        "\n",
        "        gl = ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.5, linestyle='--')\n",
        "        gl.top_labels = gl.right_labels = False\n",
        "        ax.set_title(f'{season}\\n{len(season_files[season])} passes | {pts:,} pts',\n",
        "                     fontsize=12, fontweight='bold')\n",
        "\n",
        "    fig.suptitle('SWOT L3 SSHA — Season-wise Mesoscale Eddy Signatures\\n'\n",
        "                 f'({LAT_BOUNDS[0]}°–{LAT_BOUNDS[1]}°N, {LON_BOUNDS[0]}°–{LON_BOUNDS[1]}°E)',\n",
        "                 fontsize=16, fontweight='bold', y=1.02)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('seasonal_ssha_eddies.png', dpi=200, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print('Saved → seasonal_ssha_eddies.png')\n",
        "else:\n",
        "    print('No seasonal data available.')\n",
        "\n",
        "# ── Day-wise: group by date and plot daily composites ──\n",
        "day_files = defaultdict(list)\n",
        "for f in all_parsed_files:\n",
        "    day_files[f['start_datetime'].strftime('%Y-%m-%d')].append(f)\n",
        "\n",
        "print(f'\\nTotal unique days with data: {len(day_files)}')\n",
        "for d in sorted(day_files.keys()):\n",
        "    print(f'  {d}: {len(day_files[d])} passes')\n",
        "\n",
        "# Plot first 6 days as sample daily composites\n",
        "sample_days = sorted(day_files.keys())[:6]\n",
        "if sample_days:\n",
        "    ncols = min(3, len(sample_days))\n",
        "    nrows = (len(sample_days) + ncols - 1) // ncols\n",
        "    fig, axes = plt.subplots(nrows, ncols, figsize=(8*ncols, 8*nrows),\n",
        "                             subplot_kw={'projection': ccrs.PlateCarree()})\n",
        "    if nrows * ncols == 1:\n",
        "        axes = np.array([axes])\n",
        "    axes = axes.ravel()\n",
        "\n",
        "    for idx, day in enumerate(sample_days):\n",
        "        ax = axes[idx]\n",
        "        ax.set_extent([LON_BOUNDS[0], LON_BOUNDS[1],\n",
        "                       LAT_BOUNDS[0], LAT_BOUNDS[1]], crs=ccrs.PlateCarree())\n",
        "        ax.add_feature(cfeature.LAND, facecolor='lightgray', edgecolor='black')\n",
        "        ax.add_feature(cfeature.OCEAN, facecolor='#e6f2ff', alpha=0.3)\n",
        "        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)\n",
        "\n",
        "        sc = None\n",
        "        pts = 0\n",
        "        for f in day_files[day]:\n",
        "            try:\n",
        "                lat, lon, ssha, _ = load_l3_data(f['filepath'])\n",
        "                mask = ((lat >= LAT_BOUNDS[0]) & (lat <= LAT_BOUNDS[1]) &\n",
        "                        (lon >= LON_BOUNDS[0]) & (lon <= LON_BOUNDS[1]))\n",
        "                if np.sum(mask) > 0:\n",
        "                    sc = ax.scatter(lon[mask], lat[mask], c=ssha[mask],\n",
        "                                   cmap='RdBu_r', s=0.5, alpha=0.8,\n",
        "                                   vmin=-0.5, vmax=0.5,\n",
        "                                   transform=ccrs.PlateCarree())\n",
        "                    pts += np.sum(mask)\n",
        "            except Exception:\n",
        "                pass\n",
        "\n",
        "        if sc is not None:\n",
        "            plt.colorbar(sc, ax=ax, shrink=0.6, pad=0.02).set_label('SSHA (m)')\n",
        "\n",
        "        gl = ax.gridlines(draw_labels=True, linewidth=0.5, alpha=0.4, linestyle='--')\n",
        "        gl.top_labels = gl.right_labels = False\n",
        "        ax.set_title(f'{day}\\n{len(day_files[day])} passes | {pts:,} pts',\n",
        "                     fontsize=11, fontweight='bold')\n",
        "\n",
        "    # Hide unused axes\n",
        "    for idx in range(len(sample_days), len(axes)):\n",
        "        axes[idx].set_visible(False)\n",
        "\n",
        "    fig.suptitle('SWOT L3 — Day-wise SSHA Composites (sample)',\n",
        "                 fontsize=15, fontweight='bold', y=1.02)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('daily_ssha_composites.png', dpi=200, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print('Saved → daily_ssha_composites.png')\n",
    ]
}

# Insert new cells after the grand summary (index 5)
nb["cells"].insert(6, composite_cell)
nb["cells"].insert(7, cyclone_cell)
nb["cells"].insert(8, seasonal_cell)

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"\nDone! Notebook now has {len(nb['cells'])} cells.")
print("Changes applied:")
print("  1. all_cycle_dirs = [] initialized before os.walk loop")
print("  2. PROCESS_ALL_CYCLES → PROCESS_ALL fixed in grand summary")
print("  3. NEW Cell 7: Forward + Backward composite on one image")
print("  4. NEW Cell 8: Cyclone before/after analysis (Shakti, Remal, Dana)")
print("  5. NEW Cell 9: Season-wise & day-wise SSHA analysis")
