"""Fix swoth_l3_data_plot copy.ipynb — replace broken cells 2, 5, 6."""
import json

path = r"c:\Users\abhik\Desktop\project related work\swoth_l3_data_plot copy.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# ── Cell 2 (index 1): Configuration & Discovery ──
nb["cells"][1]["source"] = [
    "# ===================================================================\n",
    "# CONFIGURATION\n",
    "# ===================================================================\n",
    "\n",
    'BASE_DIR = r"Y:\\level 3 ocean basic files\\Basic_filters_cyclones"\n',
    "\n",
    "# BOB region bounds\n",
    "LAT_BOUNDS = (5, 25)\n",
    "LON_BOUNDS = (80, 100)\n",
    "\n",
    "# ===================================================================\n",
    "# AUTO-DISCOVER ALL FOLDERS WITH .nc FILES (recursive)\n",
    "# ===================================================================\n",
    "all_cycle_dirs = []   # initialise before the loop\n",
    "\n",
    "for root, dirs, files in os.walk(BASE_DIR):\n",
    '    nc_files = [f for f in files if f.lower().endswith(".nc")]\n',
    "    if nc_files:\n",
    "        rel_path = os.path.relpath(root, BASE_DIR)\n",
    "        all_cycle_dirs.append({\n",
    "            'path':     root,\n",
    "            'folder':   rel_path,\n",
    "            'nc_count': len(nc_files),\n",
    "        })\n",
    "\n",
    'print(f"Total folders with .nc files found: {len(all_cycle_dirs)}")\n',
    'print(f"\\nFolders discovered:")\n',
    "for c in all_cycle_dirs:\n",
    """    print(f"  \\U0001f4c1 {c['folder']:<40} {c['nc_count']:>4} files")\n""",
    "\n",
    "# ===================================================================\n",
    "# SELECTION CONTROL\n",
    "# ===================================================================\n",
    "PROCESS_ALL   = True\n",
    'FOLDER_FILTER = "Shakti"\n',
    "\n",
    "if PROCESS_ALL:\n",
    "    selected_cycles = all_cycle_dirs\n",
    '    print(f"\\n>>> Mode: ALL FOLDERS ({len(selected_cycles)} folders)")\n',
    "else:\n",
    "    selected_cycles = [\n",
    "        c for c in all_cycle_dirs\n",
    """        if FOLDER_FILTER.lower() in c['folder'].lower()\n""",
    "    ]\n",
    """    print(f"\\n>>> Mode: FILTER by '{FOLDER_FILTER}' -> {len(selected_cycles)} folders matched")\n""",
    "    for c in selected_cycles:\n",
    """        print(f"    ✔ {c['folder']}")\n""",
    "\n",
    """print(f"\\nFolders to process: {[c['folder'] for c in selected_cycles]}")\n""",
    "\n",
    "# ===================================================================\n",
    "# PARSE L3 BASIC FILENAMES\n",
    "# ===================================================================\n",
    "def parse_l3_filename(filepath):\n",
    "    basename = os.path.basename(filepath)\n",
    '    pattern = (r"SWOT_L3_LR_SSH_Basic_(\\d{3})_(\\d{3})_"\n',
    '               r"(\\d{8}T\\d{6})_(\\d{8}T\\d{6})_v(\\d+\\.\\d+)\\.nc")\n',
    "    match = re.match(pattern, basename)\n",
    "    if match:\n",
    "        return {\n",
    "            'filename':       basename,\n",
    "            'filepath':       filepath,\n",
    "            'cycle':          int(match.group(1)),\n",
    "            'pass_number':    int(match.group(2)),\n",
    "            'start_datetime': datetime.strptime(match.group(3), '%Y%m%dT%H%M%S'),\n",
    "            'end_datetime':   datetime.strptime(match.group(4), '%Y%m%dT%H%M%S'),\n",
    "            'version':        match.group(5),\n",
    "        }\n",
    "    return None\n",
]

# ── Cell 5 (index 4): Plotting loop ──
nb["cells"][4]["source"] = [
    "# ===================================================================\n",
    "# LOOP THROUGH ALL SELECTED FOLDERS — Plot Forward & Backward Passes\n",
    "# ===================================================================\n",
    "\n",
    "all_results = {}\n",
    "\n",
    "for cycle_info in selected_cycles:\n",
    "    folder_label = cycle_info['folder']\n",
    "    cycle_dir    = cycle_info['path']\n",
    "\n",
    '    print("\\n" + "#" * 100)\n',
    '    print(f"#  FOLDER: {folder_label}")\n',
    '    print("#" * 100)\n',
    "\n",
    "    # ------ Scan and parse files ------\n",
    '    nc_files = glob.glob(os.path.join(cycle_dir, "*.nc"))\n',
    '    print(f"\\n  Total .nc files found: {len(nc_files)}")\n',
    "\n",
    "    if not nc_files:\n",
    '        print(f"  ⚠️ No .nc files in {cycle_dir}, skipping...")\n',
    "        all_results[folder_label] = {\n",
    "            'fwd_plotted': [], 'fwd_no_data': [],\n",
    "            'bwd_plotted': [], 'bwd_no_data': [], 'skipped': True\n",
    "        }\n",
    "        continue\n",
    "\n",
    "    parsed = [parse_l3_filename(f) for f in nc_files]\n",
    "    parsed = [p for p in parsed if p is not None]\n",
    '    print(f"  Successfully parsed: {len(parsed)} files")\n',
    "\n",
    "    if not parsed:\n",
    '        print(f"  ⚠️ No valid L3 Basic files parsed, skipping...")\n',
    "        all_results[folder_label] = {\n",
    "            'fwd_plotted': [], 'fwd_no_data': [],\n",
    "            'bwd_plotted': [], 'bwd_no_data': [], 'skipped': True\n",
    "        }\n",
    "        continue\n",
    "\n",
    "    # Keep unique granules (highest version if duplicates)\n",
    "    granule_map = defaultdict(list)\n",
    "    for p in parsed:\n",
    "        key = (p['cycle'], p['pass_number'],\n",
    "               p['start_datetime'].strftime('%Y%m%dT%H%M%S'))\n",
    "        granule_map[key].append(p)\n",
    "\n",
    "    files_info = [max(files, key=lambda x: x['version'])\n",
    "                  for files in granule_map.values()]\n",
    "    files_info.sort(key=lambda x: x['pass_number'])\n",
    "\n",
    "    forward_files  = [f for f in files_info if f['pass_number'] % 2 == 1]\n",
    "    backward_files = [f for f in files_info if f['pass_number'] % 2 == 0]\n",
    "\n",
    "    cycles_in_folder = sorted(set(f['cycle'] for f in files_info))\n",
    '    print(f"  Unique passes: {len(files_info)}  |  Forward: {len(forward_files)}"\n',
    '          f"  |  Backward: {len(backward_files)}")\n',
    '    print(f"  Cycles in this folder: {cycles_in_folder}")\n',
    "\n",
    "    # ------ Date/Time info ------\n",
    "    dates = sorted(set(f['start_datetime'] for f in files_info))\n",
    """    print(f"  Date range: {min(dates).strftime('%Y-%m-%d')} -> "\n""",
    """          f"{max(dates).strftime('%Y-%m-%d')} ({(max(dates)-min(dates)).days} days)")\n""",
    "\n",
    """    safe_label = folder_label.replace("\\\\", "_").replace("/", "_")\n""",
    "\n",
    "    # ------ PLOT FORWARD PASSES ------\n",
    """    print(f"\\n  {'─'*80}")\n""",
    '    print(f"  FORWARD PASSES — {folder_label}  |  {len(forward_files)} files")\n',
    """    print(f"  {'─'*80}")\n""",
    "\n",
    "    fwd_plotted, fwd_no_data = plot_passes(\n",
    "        forward_files,\n",
    '        title_label=f"{folder_label} — Forward Passes (Ascending / Odd)",\n',
    "        lat_bounds=LAT_BOUNDS,\n",
    "        lon_bounds=LON_BOUNDS,\n",
    '        save_name=f"bob_{safe_label}_forward_passes.png"\n',
    "    )\n",
    "\n",
    "    # ------ PLOT BACKWARD PASSES ------\n",
    """    print(f"\\n  {'─'*80}")\n""",
    '    print(f"  BACKWARD PASSES — {folder_label}  |  {len(backward_files)} files")\n',
    """    print(f"  {'─'*80}")\n""",
    "\n",
    "    bwd_plotted, bwd_no_data = plot_passes(\n",
    "        backward_files,\n",
    '        title_label=f"{folder_label} — Backward Passes (Descending / Even)",\n',
    "        lat_bounds=LAT_BOUNDS,\n",
    "        lon_bounds=LON_BOUNDS,\n",
    '        save_name=f"bob_{safe_label}_backward_passes.png"\n',
    "    )\n",
    "\n",
    "    # ------ Per-folder summary ------\n",
    "    all_results[folder_label] = {\n",
    "        'fwd_plotted': fwd_plotted, 'fwd_no_data': fwd_no_data,\n",
    "        'bwd_plotted': bwd_plotted, 'bwd_no_data': bwd_no_data,\n",
    "        'total_files': len(files_info), 'skipped': False,\n",
    "        'cycles': cycles_in_folder,\n",
    "    }\n",
    "\n",
    '    print(f"\\n  ✅ {folder_label} complete — "\n',
    '          f"Forward: {len(fwd_plotted)} passes | Backward: {len(bwd_plotted)} passes")\n',
    "\n",
    'print("\\n" + "=" * 100)\n',
    'print("  ALL FOLDERS PROCESSED!")\n',
    'print("=" * 100)\n',
]

# ── Cell 6 (index 5): Grand summary ──
nb["cells"][5]["source"] = [
    "# ===================================================================\n",
    "# GRAND SUMMARY — ALL FOLDERS\n",
    "# ===================================================================\n",
    'print("\\n" + "=" * 100)\n',
    'print("  GRAND SUMMARY — ALL FOLDERS — BOB REGION COVERAGE")\n',
    'print("=" * 100)\n',
    "\n",
    "total_fwd = 0\n",
    "total_bwd = 0\n",
    "total_fwd_no = 0\n",
    "total_bwd_no = 0\n",
    "\n",
    "for folder_label in sorted(all_results.keys()):\n",
    "    res = all_results[folder_label]\n",
    "    if res['skipped']:\n",
    '        print(f"\\n  {folder_label}: ⚠️ SKIPPED (no valid files)")\n',
    "        continue\n",
    "\n",
    "    nf    = len(res['fwd_plotted'])\n",
    "    nb    = len(res['bwd_plotted'])\n",
    "    nf_no = len(res['fwd_no_data'])\n",
    "    nb_no = len(res['bwd_no_data'])\n",
    "    total_fwd    += nf\n",
    "    total_bwd    += nb\n",
    "    total_fwd_no += nf_no\n",
    "    total_bwd_no += nb_no\n",
    "\n",
    "    cycles_str = ', '.join(str(c) for c in res.get('cycles', []))\n",
    '    print(f"\\n  📁 {folder_label}  (cycles: {cycles_str})")\n',
    '    print(f"    Forward  — ✓ In region: {nf:3d} passes  |  ✗ No data: {nf_no:3d} passes")\n',
    '    print(f"    Backward — ✓ In region: {nb:3d} passes  |  ✗ No data: {nb_no:3d} passes")\n',
    """    print(f"    Passes plotted: {sorted(res['fwd_plotted'] + res['bwd_plotted'])}")\n""",
    "\n",
    "processed = len([r for r in all_results.values() if not r['skipped']])\n",
    """print(f"\\n{'─'*100}")\n""",
    'print(f"  TOTALS ACROSS {processed} FOLDER(S):")\n',
    'print(f"    Forward passes with data  : {total_fwd}")\n',
    'print(f"    Backward passes with data : {total_bwd}")\n',
    'print(f"    Total passes with data    : {total_fwd + total_bwd}")\n',
    'print(f"    Forward passes no data    : {total_fwd_no}")\n',
    'print(f"    Backward passes no data   : {total_bwd_no}")\n',
    """mode_str = "ALL FOLDERS" if PROCESS_ALL else f"FILTER: '{FOLDER_FILTER}'"\n""",
    'print(f"\\n    Mode: {mode_str}")\n',
    'print("=" * 100)\n',
]

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("✅ All 3 cells (2, 5, 6) replaced successfully!")
